### ISSUE TITLE
Navbar Bug

### ISSUE THREAD

**Issue by MZRCode** [SiebeBaree/coinz-app#11]
The navbar menu takes up the **whole** screen on **phones** and won't go away even if you click on it

**Comment by SiebeBaree** [comment]
This repository is not being updated anymore. A new version of the website using Next.js 13 with app router is being developed. See: https://github.com/SiebeBaree/Coinz/tree/v4

The new version does not have mobile support yet, I'm still working on it. But the new version will use shadcn/ui for a mobile navbar.
